# -*- coding: utf-8 -*-
"""chapter02_03

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zvinsHl54nWLXzkxDomGatd4rrsFZBTO
"""

#행렬에서 최종행렬의 최솟값 카드 뽑기

n,m = map(int,input().split())# n x m 행렬 만든다

for i in range(n):
    row1 = map(int,input().split())
    
    min1 = min(row1)
    

print(min1)

