# -*- coding: utf-8 -*-
"""2480

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15XHvsoTSSIiEvbErvz5gfTlu19kG6uwB
"""

dice1,dice2,dice3 = map(int,input().split())


if dice1 == dice2 == dice3:
    print(10000 + dice1*1000)

elif dice1 == dice2:
    print(1000 + dice1 * 100)

elif dice1 == dice3:
    print(1000 + dice1 * 100)

elif dice2 == dice3:
    print(1000 + dice2 * 100)

else:
    print(100 * max(dice1,dice2,dice3))

#https://rsh1994.tistory.com/15