# -*- coding: utf-8 -*-
"""자료형,type.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X3NUirQM-KjIAMj-QmFdvfK2sl6cvr_H
"""

#자료형:여러 종류의 데이터를 말하고, 구분을 해야한다.
# 왜냐하면, 다른 종류끼리는 연산이 되지 않는다.
# 데이터 타입: 정수, 실수, 문자열, 리스트, 튜플, 집합, 딕셔너리
# 자료형 함수:type()

a = 100
b = 3.14
c = "korea"
lst = [1,2,3,4,5]
tpl = (1,2,3,4,5)
s = {1,2,3,4,5}
dic = {'k': 32, 't': 21} #{'키': 값}구조로 하나의 사전 형태

print(a, type(a))#숫자형- 정수
print(b, type(b))#숫자형 - 실수
print(c, type(c))#문자형
print(lst, type(lst))#리스트
print(tpl, type(tpl))#튜플
print(s, type(s)) # 집합,중복 안됨
print(dic, type(dic))#딕셔너리

